### ISSUE TITLE
Default security group has the wrong port configured

### ISSUE THREAD

**Issue by jeremiasroma** [DNXLabs/terraform-aws-eb-windows#10]
### Description. What happened?

The security group created by the module allows connection to port 22 but this module is supposed to create only Windows instance, therefore it should allow RDP connections.

Also, the security group should be configurable, allowing other ports/connections to be set up.

### Steps to reproduce

Apply the default module and check the created security group

### Actual behavior

The security group created by the module allows connection to port 22 but this module is supposed to create only Windows instance, therefore it should allow RDP connections.

### Occurrence

Frequently

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brunodasilvalenga** [comment]
Already fixed.
